const basedList = {
  response: {
    header: {
      resultCode: "0000",
      resultMsg: "OK",
    },
    body: {
      items: {
        item: [
          {
            contentId: "4",
            facltNm: "(주)디노담양힐링파크 지점",
            lineIntro: "담양 힐링파크에서 일상 속 쌓인 스트레스를 풀어보자",
            intro:
              "담양군 봉산면 기곡리에 위치한 힐링파크 담양점은 도심과 떨어져 조용히 숲과 자연에서 자유로이 쉴수 있는 힐링파크다. 이곳은 기존 봉산관광농원이라는 이름으로 1998년 농림부 1등급 판정을 받은 시설로 어느 휴양지에서도 느끼지 못했던 색다른 휴식과 즐거움을 동시에 느낄 수 있다.  담양 힐링파크는 대한민국에서 둘째가라면 서러울 정도로 많은 편의시설을 자랑하고 있는데 책을 좋아하는 사람이라면 누구든 이용 가능한 실내 독서실과 저수지낚시터가 있다. 또한 족구, 배드민턴 등 함께 뛰며 게임할 수 있는 족구장이 있으며 배드민턴은 무료 대여중이다. 이밖에도 주말 행복한 하루를 밤하늘을 보며 마감할 수 있는 주말 폭죽서비스가 있다.  이곳은 ‘동물의 왕국’이라고 해도 과언이 아닐 정도로 다양한 동물들과 시간을 보낼 수 있는데 미니동물원에서는 토끼에게 먹이도 주고 만져보며 교감할 수 있다. 그리고 담양곤충체험관이 있어 자연, 곤충과 친해질 수 있으며 이용료는 무료다. 반려동물이 출입이 가능하므로 자신의 반려동물과도 추억을 쌓을 수 있다.",
            allar: "2500",
            insrncAt: "Y",
            trsagntNo: "2016-000004호",
            bizrno: "171-29-00619",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm:
              "물놀이시설 잘 갖추어짐 실내 놀이방 실내 독서방  카라반 2동 글램핑 시설이 좋은편",
            induty: "일반야영장,카라반,글램핑",
            lctCl: "호수",
            doNm: "전라남도",
            sigunguNm: "담양군",
            zipcode: "57371",
            addr1: "전남 담양군 봉산면 탄금길 9-26",
            addr2: "",
            mapX: "126.9609528",
            mapY: "35.2714369",
            direction: "",
            tel: "061-383-5155",
            homepage: "https://healingpark.modoo.at/",
            resveUrl: "https://healingpark.modoo.at/",
            resveCl: "전화",
            manageNmpr: "2",
            gnrlSiteCo: "2",
            autoSiteCo: "0",
            glampSiteCo: "22",
            caravSiteCo: "2",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "4",
            siteMg2Width: "6",
            siteMg3Width: "0",
            siteMg1Vrticl: "6",
            siteMg2Vrticl: "7",
            siteMg3Vrticl: "0",
            siteMg1Co: "13",
            siteMg2Co: "11",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "24",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty:
              "침대,에어컨,냉장고,유무선인터넷,난방기구,취사도구,내부화장실",
            caravInnerFclty:
              "침대,TV,에어컨,냉장고,유무선인터넷,난방기구,취사도구,내부화장실",
            prmisnDe: "2016-10-27",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "4",
            swrmCo: "3",
            wtrplCo: "2",
            brazierCl: "개별",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,트렘폴린,물놀이장,놀이터,산책로,운동시설,마트.편의점",
            sbrsEtc: "",
            posblFcltyCl: "운동장,강/물놀이,농어촌체험시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "Y",
            exprnProgrm: "금붕어잡기체험",
            extshrCo: "20",
            frprvtWrppCo: "2",
            frprvtSandCo: "1",
            fireSensorCo: "24",
            themaEnvrnCl: "낚시,여름물놀이",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/4/thumb/thumb_720_4548WQ5JCsRSkbHrBAaZylrQ.jpg",
            createdtime: "2022-08-01 23:17:22",
            modifiedtime: "2022-08-01 23:17:22",
          },
          {
            contentId: "9",
            facltNm: "(주)쉐르빌리안티티",
            lineIntro: "반려견과 함께 즐기는 글램핑",
            intro:
              "(주)쉐르빌리안티티는 강원도 홍천군 서면에 자리했다. 서울양양고속도로 설악IC에서 한서중학교 방면으로 30분가량 달리면 닿는다. 이곳은 글램핑 18면을 갖췄는데, 이 가운데 6면은 반려견을 동반하고 글램핑을 만끽할 수 있다. 일반 글램핑과 별도의 구역을 마련해 반려견에 거부감을 가지고 있는 이용객에게 불편을 끼치지 않는다. 반려견 동반 글램핑의 경우 객실 외부 데크에 철망을 설치했으며, 내부에는 반려견 쿠션, 배변판, 패드, 밥그릇, 사료, 간식 등을 구비했다. 아울러 반려견 글램핑 존에는 반려견 전용 놀이터와 수영장을 부대시설로 마련했다. 반려견을 위한 정성은 매점에서도 찾아볼 수 있다. 여느 캠핑장과 달리 반려견용품을 판매하고 있기 때문이다. 일반 글램핑은 내부에 침대, TV, 냉난방기 등을 갖췄으며, 부대시설로는 탁구장, 족구장, 노래방이 있다.",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "글램핑",
            lctCl: "산,강",
            doNm: "강원도",
            sigunguNm: "홍천군",
            zipcode: "25100",
            addr1: "강원 홍천군 서면 밤벌길19번길 111",
            addr2: "",
            mapX: "127.5960926",
            mapY: "37.7015645",
            direction: "서울양양고속도로 설악IC에서 한서중학교 방면으로 30분",
            tel: "033-435-1199",
            homepage: "http://chereville.co.kr/default/index.php",
            resveUrl:
              "http://chereville.co.kr/default/reservation/01.php?top=5&sub=0",
            resveCl: "온라인실시간예약",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "18",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip:
              "인근 관광지로는 모곡밤벌유원지, 모곡레저타운, 홍천 무궁화마을이 있으며, 만남의 광장 닭갈비, 모곡참숯골 닭갈비 막국수 등의 음식점도 있다.",
            glampInnerFclty: "침대,TV,에어컨,냉장고,난방기구",
            caravInnerFclty: "",
            prmisnDe: "2016-09-13",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "4",
            swrmCo: "2",
            wtrplCo: "2",
            brazierCl: "개별",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,물놀이장,놀이터,운동장,운동시설,마트.편의점",
            sbrsEtc: "반려견 놀이터, 반려견 수영장, 탁구장, 족구장, 노래방",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/9/thumb/thumb_720_36369SPhIkIhwmImFUZ9E1pT.jpg",
            createdtime: "2022-08-01 23:17:22",
            modifiedtime: "2022-08-01 23:17:22",
          },
          {
            contentId: "10",
            facltNm: "(주)아웃오브파크",
            lineIntro: "이국적인 캐러밴과 알찬 부대시설",
            intro:
              "아웃오브파트는 강원도 춘천시 남면에 자리했다. 서울양양고속도로 강촌IC에서 엘리시안강촌 방면으로 30분가량 달리면 도착한다. 이곳은 북한강 변의 수려한 풍광을 배경으로 캐러밴 40대가 들어찼다. 고급스러움이 돋보이는 유럽피안 캐러밴과 에어스트림 캐러밴이다. 모든 캐러밴은 각기 다른 주제로 꾸몄다. 이 덕분에 욕실에 중점을 둔 객실이나 침실에 초점을 맞춘 객실 등 취향에 따라 선택하는 재미가 있다. 외부에는 어닝 아래 테이블, 의자, 노천욕탕, 바비큐 시설을 마련했다. 캠핑장의 강점 중 하나는 부대시설이다. 카페, 수영장, 찜질방, 스파, 중앙 무대, 분수, 노래방 등 고급스러움으로 치장한 시설이 차고 넘친다.",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "카라반",
            lctCl: "산,강",
            doNm: "강원도",
            sigunguNm: "춘천시",
            zipcode: "24468",
            addr1: "강원도 춘천시 남면 가옹개길 52-9",
            addr2: "",
            mapX: "127.5112565",
            mapY: "37.7278127",
            direction:
              "울양양고속도로 강촌IC에서 엘리시안강촌 방면으로 30분가량 달리면 도착",
            tel: "1522-1861-",
            homepage: "http://outofpark.com/main/",
            resveUrl: "",
            resveCl: "온라인실시간예약",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "40",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip:
              "주변에는 쁘띠프랑스, 호명호수공원, 청평호반 등이 있어 연계 관광이 용이하다. 전통손두부닭갈비, 수림닭갈비 등 음식점도 많다.",
            glampInnerFclty: "",
            caravInnerFclty:
              "침대,TV,에어컨,냉장고,난방기구,취사도구,내부화장실",
            prmisnDe: "2017-09-18",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "개별",
            sbrsCl: "운동시설",
            sbrsEtc: "수영장, 노래방, 찜질방, 카페, 중앙 무대, 분수",
            posblFcltyCl: "수영장",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "봄,여름,가을,겨울",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/10/thumb/thumb_720_1869epdMHtUyrinZWKFHDWty.jpg",
            createdtime: "2022-08-01 23:17:22",
            modifiedtime: "2022-08-01 23:17:22",
          },
          {
            contentId: "11",
            facltNm: "(주)양촌여울체험캠프",
            lineIntro: "다양한 먹거리를 체험을 할 수 있는 곳",
            intro:
              "양촌여울체험캠프는 여항산, 적석산, 인성산으로 병풍처럼 둘러 싸여 있는 캠핑장이다. 캠핑장 인근에는 아름다운 거락 숲과 맑은 물의 진전천이 고요히 흐르고 있는 곳이다. 펜션과 야영장이 함께 있는 캠핑장으로, 총 3구역으로 나뉘어져 있으며 사이트 공간이 넓어 텐트를 여유롭게 설치할 수 있어 편안히 쉴 수 있으며 이웃과의 불편함도 줄어들어 편안히 쉬다 올 수 있다.     배전함이 설치되어 있어 전기사용이 가능하며, 족구장이 있어 족구 등 배드민턴도 할 수 있으며 각종 운동을 할 수 있어 좋다. 아이들을 위한 물놀이시설은 최고다. 캠퍼가 아니더라도 입장료 3천원만 내면 누구든 이용할 수 있다.      아이들을 위한 피자 만들기체험은 인기가 많은 체험 중 하나다. 피자를 만들어 먹기까지의 과정을 아이들은 마냥 신기해하며 즐거워한다. 아이들을 위해 체험예약을 서두르는 것이 좋다. ",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "777-86-00555",
            facltDivNm: "지자체",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장,자동차야영장",
            lctCl: "산,숲",
            doNm: "경상남도",
            sigunguNm: "창원시",
            zipcode: "51795",
            addr1: "경상남도 창원시 마산합포구 진전면 의산삼일로 60",
            addr2: "",
            mapX: "128.3753007",
            mapY: "35.1365006",
            direction: "",
            tel: "055-271-2012",
            homepage: "http://www.yangchoncamp.co.kr/",
            resveUrl: "http://www.yangchoncamp.co.kr/",
            resveCl: "전화",
            manageNmpr: "4",
            gnrlSiteCo: "38",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "3",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "26",
            siteBottomCl3: "12",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2016-12-19",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "1",
            swrmCo: "1",
            wtrplCo: "1",
            brazierCl: "개별",
            sbrsCl: "전기,온수,물놀이장,산책로,마트.편의점",
            sbrsEtc: "",
            posblFcltyCl: "산책로,농어촌체험시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "Y",
            exprnProgrm: "피자만들기, 소시지, 쿠키, 방향제, 양초만들기",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "가능(소형견)",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/11/thumb/thumb_720_4031mKP95kUbSSBNbq5bSC5o.jpg",
            createdtime: "2022-08-01 23:17:22",
            modifiedtime: "2022-08-01 23:17:22",
          },
          {
            contentId: "12",
            facltNm: "(주)어반슬로우시티",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "자동차야영장,글램핑",
            lctCl: "",
            doNm: "강원도",
            sigunguNm: "춘천시",
            zipcode: "200921",
            addr1: "강원도 춘천시 남면 가옹개길 108 ",
            addr2: "",
            mapX: "127.5116915",
            mapY: "37.732632",
            direction: "",
            tel: "1899-9349-",
            homepage: "",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2015-08-04",
            operPdCl: "봄,여름,가을",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "개별",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/12/thumb/thumb_720_9644tjRknwgZZpQLpCUMVlno.jpg",
            createdtime: "2022-08-01 23:17:22",
            modifiedtime: "2022-08-01 23:17:22",
          },
          {
            contentId: "16",
            facltNm: "이스케이프 지점 (휴토피아)",
            lineIntro: "침대에 누워 즐기는 홍천강 풍경",
            intro:
              "휴토피아 글램핑은 강원도 홍천군 서면에 자리했다. 서울양양고속도로 남춘천IC에서 남춘천, 비발디파크 방면으로 10분가량 달리면 닿는다. 이곳은 글램핑 17면을 갖췄으며, 객실에는 침대, 소파, 냉난방기, TV, 냉장고가 있다. 화장실, 샤워장도 내부에 비치했다. 외부에는 전용 데크를 설치해 취사도구, 테이블, 의자, 바비큐 시설을 배치했다. 이곳의 최대 장점은 홍천강의 수려한 풍경을 눈에 담을 수 있다는 것이다. 멀리 갈 것도 없다. 글램핑 내부에서도 보이고, 외부 데크로 나오면 더욱 자세히 감상할 수 있다. 모던한 느낌의 관리소 건물에는 커피숍과 매점이 자리 잡고 있으며, 건물 앞으로 수영장, 공동 바비큐장, 개수대가 있다.",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "이정균",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm:
              "서울양양고속도로 남춘천IC에서 남춘천, 비발디파크 방면으로 10분",
            induty: "글램핑",
            lctCl: "숲,강",
            doNm: "강원도",
            sigunguNm: "홍천군",
            zipcode: "250856",
            addr1: "강원도 홍천군 서면 어유포리 282-8",
            addr2: "",
            mapX: "127.6892996",
            mapY: "37.6963001",
            direction: "",
            tel: "1599-7130-",
            homepage: "http://www.huttopia.co.kr",
            resveUrl: "http://www.huttopia.co.kr/reservations/",
            resveCl: "온라인예약대기",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "17",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip:
              "주변 관광지로는 팔봉산관광지, 반곡밤벌유원지가 있다. 인근 음식점은 홍천강에서 잡은 민물고기로 요리를 하는 강가촌식당이 있다.",
            glampInnerFclty:
              "침대,TV,에어컨,냉장고,난방기구,취사도구,내부화장실",
            caravInnerFclty: "",
            prmisnDe: "2016-04-29",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "1",
            brazierCl: "개별",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,물놀이장,운동시설,마트.편의점",
            sbrsEtc: "단체 바비큐장, 계곡",
            posblFcltyCl: "산책로,어린이놀이시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "가을단풍명소",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "봄,여름,가을,겨울",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/16/thumb/thumb_720_7281ozQmm7ppv6bLdBn7I6Xv.jpg",
            createdtime: "2022-08-01 23:17:22",
            modifiedtime: "2022-08-01 23:17:22",
          },
          {
            contentId: "17",
            facltNm: "드림랜드오토캠핑장",
            lineIntro: "캠핑과 함께 다양한 즐길 거리 가득한 오토캠핑장 ",
            intro:
              "드림랜드 오토캠핑장은 경북 영천시 고경면에 자리 잡고 있다. 영천시청을 기점으로 약 7km 거리에 있으며, 차량을 이용해 강변로, 영화로, 호국로를 차례로 거치면 닿는다. 도착까지 소요시간은 20분 남짓이다. 이곳은 도로와 인접해 접근이 쉽고 산과 계곡물이 흐르는 사이에 캠핑장을 조성했다. 불가마 찜질방, 예식장, 식당, 수영장, 자동자극장 등 다양한 부대시설을 운영 중이다. 캠핑장에는 파쇄석으로 이뤄진 자동차 야영장 135면을 마련했다. 사이트 크기는 가로 10m 세로 10m이며, 간격이 넓고 여유롭다. 개인 트레일러와 카라반 입장이 가능하고 전기, 무선인터넷을 이용할 수 있다. 캠핑장은 사계절 내내 운영하며, 예약은 전화와 온라인 실시간으로 받는다. 반려견은 동반 입장이 가능하다.  캠핑장 인근에는 영천 만불사, 영천 조양각 등 여행지가 많아 연계관광이 손쉽다. 곰탕으로 유명한 음식점 산성식당도 있다.",
            allar: "26446",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "267-06-02321",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "산,계곡",
            doNm: "경상북도",
            sigunguNm: "영천시",
            zipcode: "38904",
            addr1: "경북 영천시 고경면 고도길 38",
            addr2: "",
            mapX: "129.0005945",
            mapY: "35.9840344",
            direction: "",
            tel: "054-335-4500",
            homepage: "http://cafe.daum.net/nenm",
            resveUrl: "http://cafe.daum.net/nenm",
            resveCl: "",
            manageNmpr: "3",
            gnrlSiteCo: "135",
            autoSiteCo: "135",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "10",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "10",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "135",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "135",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2010-01-11",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "3",
            swrmCo: "1",
            wtrplCo: "3",
            brazierCl: "공동취사장",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,트렘폴린,물놀이장,놀이터,산책로,운동장,운동시설,마트.편의점",
            sbrsEtc: "찜질방, 불가마, 예식장, 식당",
            posblFcltyCl: "산책로,강/물놀이",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "15",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "10",
            themaEnvrnCl: "걷기길",
            eqpmnLendCl: "텐트,릴선,화로대,난방기구,식기",
            animalCmgCl: "가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/17/thumb/thumb_720_9880pmgY469oYPT25mRb8Yy8.jpg",
            createdtime: "2022-08-01 23:17:22",
            modifiedtime: "2022-08-01 23:17:22",
          },
          {
            contentId: "18",
            facltNm: "(주)자연인 ",
            lineIntro: "여유로운 힐링이 가능한 감성캠핑장",
            intro:
              "자연인 캠핑장은 제주시 중심가에서 5분 거리의 위치하고 있으며 펜션, 야외공연장, 카페, 공방, 레스토랑 등 다양한 부대시설이 함께 있는 캠핑장이다. 근교에 에코랜드, 용두암, 용두암해안도로, 사려니숲길 등 다양한 관광지가 인접해 있어 편리하게 여행할 수 있는 장점이 있는 캠핑장이다.    관리실 건물에는 화장실, 샤워장, 개수대가 있으며, 개수대 안에는 전자레인지, 그릇, 냄비, 컵 등의 취사도구가 구비되어 있어 언제든지 사용할 수 있어 편리하다. 캠핑장에서 운영하는 라이브 음악을 감상하며 생맥주를 마실 수 있는 ‘별빛광장’ 이 있어 맥주 한 잔이 주는 낭만의 시간을 가져보자.    깔끔한 화장실과 샤워장은 정리정돈이 잘 되어 있으며 샤워장엔 치약, 샴푸, 린스, 컨디셔너, 바디워시, 헤어드라이기 등 이 비치되어 있어 전혀 불편함 없이 편리하게 이용할 수 있다. 옷을 보관 할 수 있는 보관함까지 있다.",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "742-85-00697",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "제주시와 한라산 사이에 위치한 글램핑장.  ",
            induty: "일반야영장,글램핑",
            lctCl: "숲",
            doNm: "제주도",
            sigunguNm: "제주시",
            zipcode: "63239",
            addr1: "제주특별자치도 제주시 아란서길 110-0 ",
            addr2: "",
            mapX: "126.5399565",
            mapY: "33.4687254",
            direction: "",
            tel: "064-723-7500",
            homepage: "http://jejujayeonin.com/",
            resveUrl:
              "https://booking.naver.com/booking/3/bizes/112746/search?area=plt",
            resveCl: "온라인실시간예약",
            manageNmpr: "2",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "20",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "침대,TV,에어컨,냉장고,유무선인터넷,난방기구",
            caravInnerFclty: "",
            prmisnDe: "2016-08-26",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "1",
            swrmCo: "1",
            wtrplCo: "1",
            brazierCl: "",
            sbrsCl: "운동시설",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/18/thumb/thumb_720_7293hyzfcpcJltW5Sqm7an16.jpg",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "21",
            facltNm: "(주)태평소금 천일염 힐링캠프",
            lineIntro: "㈜태평소금 천일염힐링캠프에서 천천히 한 숨 쉬어가자.",
            intro:
              "㈜태평소금 천일염힐링캠프는 신안 증도면 지도증도로에 위치한 곳으로 소금밭 체험장 옆에 있다. 3,000평 면적에 일반야영장 9면과 카라반 10대의 시설을 갖추고 있으며, 특히 친환경 카라반 캠핑장인 만큼 천일염의 진가를 맛볼 수 있다. 이곳은 증도 슬로시티 내 위치한 곳답게 바쁜 일상 속에서 천천히 휴식을 취하기 좋은 곳이다. 바다와 갯벌이 끝없이 펼쳐진 자연을 보고 있노라면 세상 걱정 근심을 잠시나마 잊을 수 있다.    증도 태평염전은 여의도의 약 2배 면적을 자랑하는 국내최대단일염전으로 유네스코 생물권 보전지역과 동시에 아시아 최초 슬로시티로 지정된 곳이다. 거기에 람사르 습지에까지 지정되어 생태 그랜드슬램을 달성한 자랑스러운 근대 문화유산(제360호)이다. 그 어느 곳보다 캠핑을 하며 곳곳에서 소금을 체험할 수 있는 장소다. 염생식물원에서는 색색의 갖가지 염생식물을 만날 수 있고 소금밭체험은 기본, 레스토랑과 슈퍼에서 소금으로 관련된 음식을 맛볼 수 있다. ",
            allar: "3000",
            insrncAt: "N",
            trsagntNo: "26213-2016-01",
            bizrno: "371-87-00261",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm:
              "증도 슬로시티 내 위치  소금밭 체험장 옆  바로 옆에 태평염색식물원 위치",
            induty: "일반야영장",
            lctCl: "섬",
            doNm: "전라남도",
            sigunguNm: "신안군",
            zipcode: "535821",
            addr1: "전라남도 신안군 증도면 지도증도로 1053-11 ",
            addr2: "",
            mapX: "126.1776166",
            mapY: "34.9968071",
            direction:
              "네비게이션 검색 : &quot;소금박물관&quot;으로 검색하면 좀 더 빠르게 도착할 수 있다.",
            tel: "061-275-1596",
            homepage: "http://www.saltvillage.co.kr/main/index.asp",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "0",
            gnrlSiteCo: "9",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "10",
            indvdlCaravSiteCo: "0",
            sitedStnc: "3",
            siteMg1Width: "6",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "6",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "9",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "6",
            siteBottomCl3: "3",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty:
              "침대,TV,에어컨,냉장고,난방기구,취사도구,내부화장실",
            prmisnDe: "2016-05-11",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "1",
            swrmCo: "1",
            wtrplCo: "2",
            brazierCl: "개별",
            sbrsCl: "전기,장작판매,온수,물놀이장,놀이터,마트.편의점",
            sbrsEtc: "",
            posblFcltyCl: "산책로,낚시,해수욕,청소년체험시설",
            posblFcltyEtc: "",
            clturEventAt: "Y",
            clturEvent: "보물찾기",
            exprnProgrmAt: "Y",
            exprnProgrm: "소금밭 체험",
            extshrCo: "20",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "10",
            themaEnvrnCl: "일출명소,일몰명소,낚시,걷기길",
            eqpmnLendCl: "화로대",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/21/thumb/thumb_720_0101P4RZ9jhvwMhT2ZVJUof8.jpg",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "28",
            facltNm: "505펜션&캠핑(오공오)",
            lineIntro: "워터파크가 부럽지 않은 물놀이 시설을 갖춘 캠핑장",
            intro:
              "505펜션&캠핑은 충남 공주시 사곡면에 자리 잡고 있다. 공주시청을 기점으로 웅진로를 타고 연미터널과 신영터널을 거치면 닿는다. 도착까지 소요시간은 약 20분이다. 고즈넉한 시골길을 가다 적당히 가파른 언덕을 오르면 나타난다. 이곳은 웬만한 워터파크가 부럽지 않은 시설을 갖췄다. 대형 수영장과 워터슬라이드가 있어 남녀노소 누구나 물놀이 삼매경에 빠진다. 이 덕분에 한여름이면 발 디딜 틈이 없을 정도다. 일반캠핑장은 22면을 마련했는데, 사이트 크기는 가로 6m 세로 7m로 널찍하다. 개인 카라반과 트레일러도 수용할 수 있으며, 이 경우 이용료는 일반캠핑장과 같다. 관리소에서는 캠핑 장비를 빠뜨리고 온 캠퍼를 위해 릴선과 난방기구를 대여해준다.  캠핑장 주변에는 마곡사 등 공주의 유명 관광지가 많다. 인근 유구읍에는 공주 한우 등을 전문으로 내놓는 음식점이 즐비하다.",
            allar: "18810",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "307-17-69776",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "이연묵",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "워터파크가 부럽지 않은 물놀이 시설을 갖춘 캠핑장  ",
            induty: "일반야영장",
            lctCl: "숲",
            doNm: "충청남도",
            sigunguNm: "공주시",
            zipcode: "32523",
            addr1: "충남 공주시 사곡면 호계황골길 43",
            addr2: "",
            mapX: "127.0207700",
            mapY: "36.5017433",
            direction: "",
            tel: "010-7330-2505",
            homepage: "",
            resveUrl: "",
            resveCl: "온라인실시간예약",
            manageNmpr: "2",
            gnrlSiteCo: "22",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "3",
            siteMg1Width: "6",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "7",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "22",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2015-05-20",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "2",
            swrmCo: "2",
            wtrplCo: "3",
            brazierCl: "개별",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,물놀이장,놀이터,산책로,운동장,운동시설,마트.편의점",
            sbrsEtc: "",
            posblFcltyCl: "계곡 물놀이,낚시",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "40",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "액티비티,여름물놀이",
            eqpmnLendCl: "릴선,난방기구",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/28/thumb/thumb_720_9612Elzm89JB6yhSrST7k95L.jpg",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
        ],
      },
      numOfRows: 10,
      pageNo: 1,
      totalCount: 3216,
    },
  },
};

// {{locationBasedList}}?{{essentialParams}}&pageNo=1&mapX=127.1151262&mapY=37.1835657&radius=10000
const locationBasedList = {
  response: {
    header: {
      resultCode: "0000",
      resultMsg: "OK",
    },
    body: {
      items: {
        item: [
          {
            contentId: "1038",
            facltNm: "맑음터공원 캠핑장 ",
            lineIntro: "",
            intro:
              "입실 시 전동카트 지원되며, 퇴실시에는 선착순으로 전동카드 예약입니다.  그 외에는 핸드카트 이용입니다.  테크 사이트와 일반 사이트, 카라반 있습니다.  일반 사이트에는 테이블 1개가 기본으로 있습니다.  공원안에 위치해 있어 물놀이장, 놀이터, 산책로 있습니다.  이용요금은 오산 시민 할인 됩니다.",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "지자체",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "자동차야영장",
            lctCl: "도심",
            doNm: "경기도",
            sigunguNm: "오산시",
            zipcode: "18130",
            addr1: "경기도 오산시 오산천로 52-0 ",
            addr2: "",
            mapX: "127.0645246",
            mapY: "37.1382141",
            direction: "",
            tel: "031-8036-6891",
            homepage: "",
            resveUrl: "",
            resveCl: "전화",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2016-06-29",
            operPdCl: "",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "개별",
            sbrsCl: "물놀이장",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/1038/thumb/thumb_720_038385n7ORZ5dD7mERGbJPzS.jpg",
            createdtime: "2022-08-01 23:17:41",
            modifiedtime: "2022-08-01 23:17:41",
          },
          {
            contentId: "1380",
            facltNm: "봉봉자연 관광농원",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "2018.11.26 현장 방문 문의 전화시 취재 거절함",
            induty: "자동차야영장",
            lctCl: "",
            doNm: "경기도",
            sigunguNm: "용인시",
            zipcode: "449834",
            addr1: "경기도 용인시 처인구 이동면 서리 ",
            addr2: "613-2 ",
            mapX: "127.1694033",
            mapY: "37.2072847",
            direction: "",
            tel: "010-9906-2281",
            homepage: "http://www.bongcamp.com",
            resveUrl:
              "http://www.bongcamp.com/default/booking/app_online.php?topmenu=3",
            resveCl: "온라인실시간예약",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2016-01-27",
            operPdCl: "",
            operDeCl: "",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "",
            sbrsCl: "전기,장작판매,온수,물놀이장,놀이터,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/1380/thumb/thumb_720_0966ZXWJrk3rrZ5t2iu5HAo9.jpg",
            createdtime: "2022-08-01 23:17:47",
            modifiedtime: "2022-08-01 23:17:47",
          },
          {
            contentId: "3049",
            facltNm: "캠프레이크 ",
            lineIntro: "기흥 IC에서 3분 거리에 있는 아늑한 분위기의 글램핑장",
            intro:
              " 경기도 용인 캠프레이크는 신갈저수지 변에 위치한 전망 좋은 글램핑장이다. 기흥IC, 한국민속촌에서 3분 거리에 위치해 있다. 신갈 저수지 바로 옆에 위치해 캠핑장 어디에서나 저수지 전망을 즐길 수 있다.      글램핑은 패밀리 글램핑과 커플 글램핑, 그리고 글램하우스로 구성돼 있다. 패밀리글램핑과 글램하우스에는 에어컨이 설치되어 있다. 커플 글램핑에는 냉풍기가 설치되어 있다.      캠핑장내에 화장실, 샤워실, 개수대, 매점 등 편의시설이 잘 갖춰져 있다. 관리상태가 뛰어나 이용해 불편이 없다. ",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "288-81-00652",
            facltDivNm: "지자체",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "글램핑",
            lctCl: "호수",
            doNm: "경기도",
            sigunguNm: "용인시",
            zipcode: "17101",
            addr1: "경기 용인시 기흥구 동탄기흥로785번길 21-5 (고매동)",
            addr2: "캠프레이크 ",
            mapX: "127.0999378",
            mapY: "37.2276441",
            direction: "",
            tel: "010-2456-5390",
            homepage: "https://camplake.modoo.at/",
            resveUrl: "",
            resveCl: "전화",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "11",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "침대,에어컨,냉장고,유무선인터넷,난방기구",
            caravInnerFclty: "",
            prmisnDe: "2016-11-15",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "2",
            swrmCo: "2",
            wtrplCo: "1",
            brazierCl: "개별",
            sbrsCl: "전기,무선인터넷,장작판매,온수,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "20",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/3049/thumb/thumb_720_7323itITtqY5f4vW489PZhC6.jpg",
            createdtime: "2022-08-01 23:18:15",
            modifiedtime: "2022-08-01 23:18:15",
          },
          {
            contentId: "6955",
            facltNm: "MK골드캠프",
            lineIntro:
              "펫 실내 수영장, 천연잔디 운동장, 펫 콘도 갖춘 반려견 복합 테마파크",
            intro:
              " 경기도 용인의 MK골드캠프(골드펫리조트)는 국내 유일의 반려견 복합 테마파크다. 펫 실내수영장, 천연잔디 운동장을 갖추고 펫 콘도, 펫 카라반 등을 통해 동반 숙박이 가능한 객실도 운영하고 있다. 기존 골드훼미리리조트 시설인 객실일부와 글램핑, 카라반, 실내 수영장을 국내 리조트 최초로 펫 복합전용시설로 운영 중이다. 기존 운동장도 천연잔디운동장으로 탈바꿈시켜 수도권 반려견의 놀이터로 운영 중이다. 특히 사계절 수온이 유지되는 반려견 실내수영장은 24시간 수질정화 시스템으로 항상 깨끗한 수질을 유지하고 있다. 하이드로바스, 에어탱크, 초대형 드라이룸까지 완비했다. 캠핑장은 소중형견용 콘도 4개 객실을 비롯해 카라반, 글램핑 등으로 구성돼 있다. 반려동물 쿠션과 밥그릇, 급수기, 배변패드 등 필요한 물품이 배치돼 있다. ",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "5월 개장",
            induty: "일반야영장,카라반,글램핑",
            lctCl: "산,숲",
            doNm: "경기도",
            sigunguNm: "용인시",
            zipcode: "446807",
            addr1: "경기도 용인시 기흥구 고매동 기흥단지로 398 ",
            addr2: "골드CC클럽하우스 ",
            mapX: "127.1369537",
            mapY: "37.2169109",
            direction: "",
            tel: "031-286-9111",
            homepage: "https://goldpetresort.modoo.at/",
            resveUrl:
              "https://booking.naver.com/booking/3/bizes/42045/search?area=plt",
            resveCl: "",
            manageNmpr: "5",
            gnrlSiteCo: "2",
            autoSiteCo: "0",
            glampSiteCo: "17",
            caravSiteCo: "3",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "5",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "6",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty:
              "침대,TV,에어컨,냉장고,유무선인터넷,난방기구,취사도구,내부화장실,내부샤워실",
            caravInnerFclty:
              "침대,TV,에어컨,냉장고,유무선인터넷,난방기구,취사도구,내부화장실,내부샤워실",
            prmisnDe: "2016-02-01",
            operPdCl: "봄",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "2",
            swrmCo: "2",
            wtrplCo: "2",
            brazierCl: "개별",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "9",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "액티비티",
            eqpmnLendCl: "",
            animalCmgCl: "가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/6955/thumb/thumb_720_9935dNBS8v0qUcgtVsUi84Mi.jpg",
            createdtime: "2022-08-01 23:18:30",
            modifiedtime: "2022-08-01 23:18:30",
          },
          {
            contentId: "7171",
            facltNm: "싱글벙글 캠핑장 ",
            lineIntro: "",
            intro:
              "싱글벙글 캠핑장은 육계농장과 농원을 함께 운영하고 있는 캠핑장이다. 파쇄석과 강자갈로 된 사이트가 마련되어 있으며 어린이 물놀이장과 모래 놀이장이 있어 가족단위의 소규모 캠퍼들이 방문하기 좋은 곳이다. 주변 관광지로는 무봉산과 물향기수목원, 와우정사 등이 있다. ",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "제2015-000003호",
            bizrno: "444-29-00026",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "자동차야영장",
            lctCl: "산,숲",
            doNm: "경기도",
            sigunguNm: "용인시",
            zipcode: "17126",
            addr1: "경기 용인시 처인구 이동읍 상덕로 95-62",
            addr2: "855-1 ",
            mapX: "127.1586644",
            mapY: "37.2120767",
            direction: "",
            tel: "",
            homepage: "http://cafe.naver.com/smilecamping/",
            resveUrl:
              "http://www.campinggo.co.kr/html/new_fcal.php?ysyear=2011&ysmonth=7&seq=36",
            resveCl: "온라인실시간예약",
            manageNmpr: "2",
            gnrlSiteCo: "60",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "60",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "49",
            siteBottomCl3: "11",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2015-04-14",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "4",
            swrmCo: "7",
            wtrplCo: "12",
            brazierCl: "개별",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,트렘폴린,물놀이장,놀이터,산책로,운동장,운동시설,마트.편의점",
            sbrsEtc: "",
            posblFcltyCl: "운동장,강/물놀이,농어촌체험시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "40",
            frprvtWrppCo: "10",
            frprvtSandCo: "4",
            fireSensorCo: "0",
            themaEnvrnCl:
              "일출명소,낚시,봄꽃여행,가을단풍명소,겨울눈꽃명소,걷기길",
            eqpmnLendCl: "릴선,화로대",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl: "",
            createdtime: "2022-08-01 23:18:40",
            modifiedtime: "2022-08-01 23:18:40",
          },
          {
            contentId: "7324",
            facltNm: "소풍캠핑장",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "",
            doNm: "경기도",
            sigunguNm: "용인시",
            zipcode: "17137",
            addr1: "경기 용인시 처인구 이동읍 경기동로785번길 30",
            addr2: "",
            mapX: "127.2056205",
            mapY: "37.1336407",
            direction: "",
            tel: "010-4707-0331",
            homepage: "",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2018-06-26",
            operPdCl: "",
            operDeCl: "",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl: "",
            createdtime: "2022-08-01 23:18:46",
            modifiedtime: "2022-08-01 23:18:46",
          },
          {
            contentId: "8049",
            facltNm: "골드펫리조트",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "",
            doNm: "경기도",
            sigunguNm: "용인시",
            zipcode: "17087",
            addr1: "경기 용인시 기흥구 기흥단지로 406 (고매동, 골드훼미리콘도)",
            addr2: "",
            mapX: "127.1387381",
            mapY: "37.2210183",
            direction: "",
            tel: "031-286-9111",
            homepage: "",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2016-02-01",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "개별",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl: "",
            createdtime: "2022-08-01 23:19:17",
            modifiedtime: "2022-08-01 23:19:17",
          },
          {
            contentId: "100446",
            facltNm: "아르테오스 빌리지",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "",
            doNm: "경기도",
            sigunguNm: "용인시",
            zipcode: "17126",
            addr1: "경기 용인시 처인구 이동읍 백자로260번길 6-2",
            addr2: "",
            mapX: "127.1756001",
            mapY: "37.2018971",
            direction: "",
            tel: "",
            homepage: "",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2022-06-21",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "개별",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl: "",
            createdtime: "2022-08-01 23:19:23",
            modifiedtime: "2022-08-01 23:19:23",
          },
        ],
      },
      numOfRows: 8,
      pageNo: 1,
      totalCount: 8,
    },
  },
};

// {{searchList}}?{{essentialParams}}&keyword=연천 전곡리유적 구석기 체험숲
const searchList = {
  response: {
    header: {
      resultCode: "0000",
      resultMsg: "OK",
    },
    body: {
      items: {
        item: [
          {
            contentId: "7826",
            facltNm: "연천 전곡리유적 구석기 체험숲",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "",
            doNm: "경기도",
            sigunguNm: "연천군",
            zipcode: "11027",
            addr1: "경기 연천군 전곡읍 평화로495번길 89",
            addr2: "",
            mapX: "127.0656618",
            mapY: "38.0127419",
            direction: "",
            tel: "031-839-2564",
            homepage: "",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2020-01-16",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "개별",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl: "",
            createdtime: "2022-08-01 23:19:07",
            modifiedtime: "2022-08-01 23:19:07",
          },
        ],
      },
      numOfRows: 1,
      pageNo: 1,
      totalCount: 1,
    },
  },
};

// {{imageList}}?{{essentialParams}}&contentId=3429
const imageList = {
  response: {
    header: {
      resultCode: "0000",
      resultMsg: "OK",
    },
    body: {
      items: {
        item: [
          {
            contentId: "3429",
            serialnum: "289341",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/7798D931eCFr52PoJOTNrEdo.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289342",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/1889dK3DjvzPxKGqLYH3KpmI.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289343",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/7372o5nDlM0DdHN6hJ5oWwo5.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289344",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/0916eFJoam5ynPYgFvRFJV2N.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289345",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/9457gfjfFWLhgIIF5YqCitGT.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289346",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/3642WsbtTCVejCmrGoAgV5ql.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289347",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/7548Mkul16whJInnbRkHFQ0W.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289348",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/9437xzMzjrQINOTXFq18svzS.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289349",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/999925X0C8DzKX6wxyCn6J8j.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
          {
            contentId: "3429",
            serialnum: "289350",
            imageUrl:
              "https://gocamping.or.kr/upload/camp/3429/4413riwk0REwoDTNeuOA5hdm.jpg",
            createdtime: "2022-08-01 23:18:22",
            modifiedtime: "2022-08-01 23:18:22",
          },
        ],
      },
      numOfRows: 10,
      pageNo: 1,
      totalCount: 25,
    },
  },
};
