export const DummyData = {
  response: {
    header: {
      resultCode: "0000",
      resultMsg: "OK",
    },
    body: {
      items: {
        item: [
          {
            contentId: "57",
            facltNm: "The Star 오토캠핑장",
            lineIntro:
              "낭만적인 여수밤바다 전망 포인트 No.1. TheStar 오토캠핑장",
            intro:
              "여수시 돌산읍에 위치한 TheStar 오토캠핑장은 여수만이 내려다보이는 전망을 감상할 수 있는 캠핑장으로, 낮에는 여수만의 푸른바다를 보며 바쁜 일상 속 쉼을 얻어갈 수 있고, 밤에는 아름다운 밤바다와 호수에 정박 중인 선박의 불빛을 보며 감성적인 밤을 즐길 수 있다. 또한 주변의 낚시 포인트에서는 깨끗한 여수바다의 물고기가 황금어장을 이룬다.    이곳은 2,020평 규모에 일반야영장 9면, 오토캠핑장 19면, 카라반 2대로 이루어졌으며 모든 사이트는 데크로 구성되어 있다. 깨끗하고 쾌적한 각종 편의시설이 완비되어 있어 캠핑을 편안히 즐길 수 있다. 반려동물 출입이 가능하지만 동행할 경우 사전 예약 시 반드시 고지해야 한다.  한편, TheStar 오토캠핑장은 돌산공원, 여수해상케이블카, 여수해양공원, 아쿠아플라넷, 향일암 등 여수의 관광지와도 가까운 거리에 위치해 있어 베이스캠프로 사용하기도 좋다.",
            allar: "2020",
            insrncAt: "N",
            trsagntNo: "",
            bizrno: "336-68-00215",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "오션뷰, 데크, 깨끗, 쾌적",
            induty: "일반야영장,자동차야영장,카라반",
            lctCl: "해변,섬,숲",
            doNm: "전라남도",
            sigunguNm: "여수시",
            zipcode: "59770",
            addr1: "전남 여수시 돌산읍 상하동길 268",
            addr2: "",
            mapX: "127.7818433",
            mapY: "34.7181692",
            direction: "",
            tel: "061-641-1490",
            homepage: "http://www.thestarauto.com/",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "2",
            gnrlSiteCo: "9",
            autoSiteCo: "19",
            glampSiteCo: "0",
            caravSiteCo: "2",
            indvdlCaravSiteCo: "0",
            sitedStnc: "3",
            siteMg1Width: "4",
            siteMg2Width: "4",
            siteMg3Width: "0",
            siteMg1Vrticl: "4",
            siteMg2Vrticl: "8",
            siteMg3Vrticl: "0",
            siteMg1Co: "15",
            siteMg2Co: "13",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "28",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "침대,TV,에어컨,냉장고,유무선인터넷,난방기구",
            prmisnDe: "2018-01-15",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "2",
            swrmCo: "2",
            wtrplCo: "1",
            brazierCl: "개별",
            sbrsCl: "전기,무선인터넷,장작판매,온수,물놀이장,놀이터,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "산책로,낚시,해수욕,청소년체험시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "18",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl:
              "일출명소,일몰명소,낚시,봄꽃여행,여름물놀이,가을단풍명소,걷기길",
            eqpmnLendCl: "화로대",
            animalCmgCl: "가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/57/thumb/thumb_720_8045usCSpmaGB9XJvDDXLikG.jpg",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "59",
            facltNm: "VIP레저타운",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "자동차야영장",
            lctCl: "",
            doNm: "강원도",
            sigunguNm: "원주시",
            zipcode: "26357",
            addr1: "강원도 원주시 지정면 지정로 1393",
            addr2: "",
            mapX: "127.7839463",
            mapY: "37.389235",
            direction: "",
            tel: "031-774-7771",
            homepage: "http://place.map.daum.net/25510848",
            resveUrl: "",
            resveCl: "전화",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2017-07-11",
            operPdCl: "",
            operDeCl: "",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "가능",
            tourEraCl: "",
            firstImageUrl: "",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "60",
            facltNm: "VIP오토캠핑장 ",
            lineIntro:
              "맑은 공기 속에서 밤하늘의 별을 보며 잠들 수 있는 캠핑장.",
            intro:
              "VIP오토캠핑장은 아름다운 산과 맑은 계곡으로 둘러싸여진 자연 속의 캠핑장이다. 펜션과 방갈로 야영장의 구성으로 되어있는 캠핑장은 20여 개의 파쇄석 사이트를 가지고 있으며 사이트 공간이 여유로워 텐트를 편하게 설치 할 수 있어 좋다. 전기 배전함은 6~8사이트가 함께 사용하므로 30M 릴선을 준비해야 한다.    깨끗한 화장실은 칸이 넉넉하게 있어 기다릴 필요 없이 이용해서 편하고, 넓고 깨끗한 샤워장은 온수도 잘나오지만 파우더 룸이 따로 있어 좋다. 최신시설의 개수대는 온수를 같이 사용할 수 있어 기름 묻힌 그릇을 씻기에 좋으며, 남녀 샤워장과 화장실이 붙어있지 않아서 그것 또한 맘에 드는 캠핑장이다.     매점이 있어 간단한 생필품을 구매할 수 있지만 차로 5분 거리에 편의점과 슈퍼가 있어 편리하다. 소형견 동반입장이 가능하나 반드시 목줄을 사용하여야 한다. 주변관광지로는 아름다운 영남알프스의 풍경과 어우러져 있는 밀양댐과 산과 물의 생동감을 그대로 살려주는  아름다운 경치를 자랑하는 단장천, 여려가지 조형물과 야생초화원이 있는 생태공원 등이 있다.",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "707-79-53   ",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "자동차야영장",
            lctCl: "산,계곡",
            doNm: "경상남도",
            sigunguNm: "밀양시",
            zipcode: "627822",
            addr1: "경상남도 밀양시 단장면 고례리 ",
            addr2: "1408-5 ",
            mapX: "128.9267335",
            mapY: "35.4972561",
            direction: "",
            tel: "010-3878-2927",
            homepage: "http://vip오토캠핑장.kr/",
            resveUrl: "http://vip오토캠핑장.kr/app/reservation_new.php",
            resveCl: "온라인실시간예약",
            manageNmpr: "2",
            gnrlSiteCo: "0",
            autoSiteCo: "28",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "28",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2015-05-26",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "1",
            swrmCo: "1",
            wtrplCo: "2",
            brazierCl: "개별",
            sbrsCl: "전기,트렘폴린",
            sbrsEtc: "",
            posblFcltyCl: "계곡 물놀이,농어촌체험시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "15",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "봄꽃여행,여름물놀이,가을단풍명소",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/60/thumb/thumb_720_0204fdACFBOe3QG3a4CC8EvA.jpg",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "61",
            facltNm: "W글램핑 ",
            lineIntro: "사랑하는 반려견과 함께 글램핑에서 하루를.",
            intro:
              "W글램핑은 각종 아웃도어를 한 번에 즐길 수 있는 글램핑이다. 글램핑은 편안한 잠자리에서부터 캠핑에 필요한 모든 도구들과 시설들을 갖추고 있어, 훌훌 몸만 떠나오면 되는 곳이다. 또한 사랑하는 반려견과 동반 입장이 가능해 반려견 캠퍼들에게 사랑받는 캠핑장이다.    캠핑장에서는 다양한 프로그램과 체험이 있어 캠퍼들이 심심할 겨를이 없다. 페인트볼 게임 ,보드게임, 피자 만들기, 붕어빵 만들기, 비어캔 치킨만들기 등이 있으며, 전기바이크 투어, 카약 투어, 낚시투어, 산악바이크(ATV)투어, 래프팅 투어까지 다양한 즐길 거리로 넘쳐나고 있다.    바비큐 상차림을 예약하면 무한리필 (돼지고기, 닭봉, 소세지, 새우, 마시멜로, 옥수수, 구이용떡, 김치 ,마늘, 고추, 상추, 깻잎, 쌈장, 소금, 참기름)로 먹을 수 있으며  햇반, 라면, 물까지 그냥 먹을 수 있다. 평일에는 전기바이크를 1시간 무상대여 해주고 있으며, 주말엔 1만원의 이용료가 있다. 전동힐은 주중 주말 무상대여 해주고 있다.",
            allar: "800",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "613-22-71623",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장,글램핑",
            lctCl: "강",
            doNm: "경상남도",
            sigunguNm: "산청군",
            zipcode: "666801",
            addr1: "경상남도 산청군 산청읍 내리 ",
            addr2: "259-5 ",
            mapX: "127.8873465",
            mapY: "35.3932118",
            direction: "",
            tel: "055-974-3642",
            homepage: "http://www.wglamping.com/",
            resveUrl: "http://www.wglamping.com/",
            resveCl: "전화",
            manageNmpr: "0",
            gnrlSiteCo: "1",
            autoSiteCo: "0",
            glampSiteCo: "14",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "5",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "15",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "15",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "침대,TV,에어컨,냉장고,유무선인터넷,난방기구",
            caravInnerFclty: "",
            prmisnDe: "2016-05-03",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "2",
            swrmCo: "2",
            wtrplCo: "2",
            brazierCl: "개별",
            sbrsCl: "전기,놀이터,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "수상레저,어린이놀이시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "Y",
            exprnProgrm:
              "전기바이크, 카약투어, 낚시투어, 산악바이크투어, 래프팅투어 페인트볼게임, 보드게임, 피자만들기, 붕어빵 만들기, 비어캔치킨 만들기",
            extshrCo: "15",
            frprvtWrppCo: "1",
            frprvtSandCo: "0",
            fireSensorCo: "15",
            themaEnvrnCl: "수상레저,여름물놀이,걷기길",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/61/thumb/thumb_720_8222j5WKjFDC4IsEb1HM2L8O.jpg",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "62",
            facltNm: "YC글램핑",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "",
            doNm: "경기도",
            sigunguNm: "연천군",
            zipcode: "11045",
            addr1: "경기 연천군 미산면 청정로 1049",
            addr2: "",
            mapX: "126.9660207",
            mapY: "38.0382263",
            direction: "",
            tel: "010-5097-6446",
            homepage: "http://www.ycglamping.com/",
            resveUrl: "http://www.ycglamping.com/",
            resveCl: "전화",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2017-04-10",
            operPdCl: "",
            operDeCl: "",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "",
            sbrsCl: "물놀이장,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/62/thumb/thumb_720_4025MWy2QC7WM50UdibHQnwW.jpg",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "63",
            facltNm: "YELLOW HILL",
            lineIntro: "",
            intro: "",
            allar: "0",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "자동차야영장",
            lctCl: "",
            doNm: "강원도",
            sigunguNm: "춘천시",
            zipcode: "24409",
            addr1: "강원도 춘천시 동산면 종자리로 224-24",
            addr2: "",
            mapX: "127.7449681",
            mapY: "37.7609521",
            direction: "",
            tel: "033-262-5656",
            homepage: "",
            resveUrl: "",
            resveCl: "현장",
            manageNmpr: "0",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2017-12-19",
            operPdCl: "",
            operDeCl: "",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "",
            sbrsCl: "",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl: "",
            createdtime: "2022-08-01 23:17:23",
            modifiedtime: "2022-08-01 23:17:23",
          },
          {
            contentId: "66",
            facltNm: "㈜씨스테이 야영장 ",
            lineIntro: "",
            intro: "",
            allar: "17000",
            insrncAt: "N",
            trsagntNo: "",
            bizrno: "482-81-10020",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "자동차야영장",
            lctCl: "섬",
            doNm: "인천시",
            sigunguNm: "옹진군",
            zipcode: "409871",
            addr1: "인천광역시 옹진군 영흥면 내리 ",
            addr2: "1212-52 ",
            mapX: "126.4683211",
            mapY: "37.2801027",
            direction: "",
            tel: "010-9076-3801",
            homepage: "",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "0",
            gnrlSiteCo: "13",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "7",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "20",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "13",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "13",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2016-02-26",
            operPdCl: "봄,여름,가을",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "2",
            swrmCo: "2",
            wtrplCo: "2",
            brazierCl: "개별",
            sbrsCl: "전기,무선인터넷,온수,물놀이장,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "8",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/66/thumb/thumb_720_1047qvq4IF1re0nhT7R1I9cv.jpg",
            createdtime: "2022-08-01 23:17:24",
            modifiedtime: "2022-08-01 23:17:24",
          },
          {
            contentId: "67",
            facltNm: "(주)제주글램핑",
            lineIntro:
              "캠핑의 자유로움과 호텔의 편안함을 느낄 수 있는 제주글램핑",
            intro:
              "제주글램핑은 천혜의 자연 경관을 제주에서 즐길 수 있는 수목원 같은 숲속 글램핑장으로  국내 최대 규모의 80여개의 글램핑 사이트를 가지고 있는 복합 휴양시설의 캠핑장이다. 글램핑장을 비롯해 세미나장, 야외수영장, 편의점, 식당 등 고품격 부대시설을 갖추고 있다.    글램핑장은 각각의 개별 정원을 갖추어 캠핑의 자유로움과 호텔의 편안함을 동시에 즐길 수 있는 카바나 텐트와, 원뿔형의 감성 캠핑을 즐길 수 있는 인디언 텐트 등. 색다른 경험을 할 수 있는 캠핑이 될 것이다. 넓은 주차장과 인디언 텐트 이용자를 위한 깨끗한 화장실, 개수대, 최신시설의 샤워장, 일반인 수영장과 아동용 수영장이 구분되어 있는 야자수가 가득한 이국적인 야외수영장 등은 제주글램핑장의 자랑이다. 그 외 농구장, 족구장, 아이들이 좋아하는 트램폴린 등 레저 활동도 여유롭게 할 수 있어 좋다.",
            allar: "7532",
            insrncAt: "Y",
            trsagntNo: "",
            bizrno: "616-86-07646",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "산,숲",
            doNm: "제주도",
            sigunguNm: "제주시",
            zipcode: "695977",
            addr1: "제주특별자치도 제주시 구좌읍 덕천리 ",
            addr2: "1288-2 ",
            mapX: "126.7521990",
            mapY: "33.4814834",
            direction: "",
            tel: "064-784-3200",
            homepage: "http://www.jeju-glamping.com",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "10",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "81",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "0",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "0",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty:
              "침대,TV,에어컨,냉장고,유무선인터넷,난방기구,취사도구,내부화장실",
            caravInnerFclty: "",
            prmisnDe: "2016-03-03",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "N",
            caravAcmpnyAt: "N",
            toiletCo: "2",
            swrmCo: "2",
            wtrplCo: "2",
            brazierCl: "불가",
            sbrsCl: "전기,온수,물놀이장,놀이터,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "N",
            exprnProgrm: "",
            extshrCo: "0",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/67/thumb/thumb_720_3217CKK1DPDRRpdb1aXDknUY.jpg",
            createdtime: "2022-08-01 23:17:24",
            modifiedtime: "2022-08-01 23:17:24",
          },
          {
            contentId: "69",
            facltNm: "가람관광농원",
            lineIntro: "합천호를 바라보며 캠핑을 즐길 수 있는 자연 학습장 ",
            intro:
              "가람펜션캠핑장은 펜션과 오토캠핑장이 함께 있는 캠핑장이다. 캠핑장 입구에는 미니 동물농장이 있어(오리, 닭, 토끼 등) 캠퍼들을 반갑게 맞아준다. 캠핑장 사이트는 파쇄석으로 되어 있으며 화장실, 개수대, 샤워장이 같은 건물에 있다. 여자 화장실에 어린이용 세면대가 따로 설치되어 있어 아이들이 혼자서도 열심히 세수를 한다.     개수대에는 전자레인지가 있어 간편한 요리를 해먹을 수 있어 편리하다. 아이들이 좋아하는  트램펄린이 설치되어 있으며, 여름철에 넓은 수영장이 운영되어 특히 아이들이 좋아한다. 캠핑장 옆으로 계곡물이 흐르고 있어 물고기 잡기와 물놀이를 즐길 수 있다. 캠핑장 한쪽으로는 사장님 내외가 유기농으로 키우신 텃밭이 있다. 주렁주렁 열려있는 고추, 상추, 토마토, 콜라비 등을 무료로 먹을 수 있다. ",
            allar: "1500",
            insrncAt: "Y",
            trsagntNo: "217-01",
            bizrno: "303- 2-27030",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm: "",
            induty: "일반야영장",
            lctCl: "산,숲,호수",
            doNm: "경상남도",
            sigunguNm: "합천군",
            zipcode: "50210",
            addr1: "경남 합천군 봉산면 인덕로 930",
            addr2: "",
            mapX: "128.0576000",
            mapY: "35.5873961",
            direction: "",
            tel: "010-9704-2582",
            homepage: "http://cafe.naver.com/hpgeni2016",
            resveUrl: "http://cafe.naver.com/hpgeni2016",
            resveCl: "",
            manageNmpr: "2",
            gnrlSiteCo: "0",
            autoSiteCo: "22",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "6",
            siteMg2Width: "0",
            siteMg3Width: "0",
            siteMg1Vrticl: "7",
            siteMg2Vrticl: "0",
            siteMg3Vrticl: "0",
            siteMg1Co: "22",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "19",
            siteBottomCl3: "3",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2017-11-14",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "1",
            swrmCo: "1",
            wtrplCo: "1",
            brazierCl: "개별",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,트렘폴린,물놀이장,놀이터,운동시설",
            sbrsEtc: "",
            posblFcltyCl: "수상레저",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "Y",
            exprnProgrm: "밤줍기체험 불루베리체험",
            extshrCo: "7",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "수상레저,낚시",
            eqpmnLendCl: "",
            animalCmgCl: "불가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/69/thumb/thumb_720_1454jkXgwy4yNn8OeOQLzV2d.jpg",
            createdtime: "2022-08-01 23:17:24",
            modifiedtime: "2022-08-01 23:17:24",
          },
          {
            contentId: "70",
            facltNm: "가래골농원 캠핑장 ",
            lineIntro: "놀거리와 체험거리 가득한 아이들의 천국",
            intro:
              "가래골농원 캠핑장은 포천시 창수면, 물 맑고 산 좋은 종현산 자락에 위치한 힐링 캠핑장이다. 4만 5천평에 달하는 대지에 가족농원 캠핑장을 모토로 텃밭과 동물농장을 가지고 있으며, 펜션과 오토캠핑장의 구성으로 되어 있는 복합적인 캠핑장이다. 가래골농원 캠핑장은 테마 별로 조성 되어진 사이트를 가지고 있다. 잣나무와 소나무가 우거져있는 소나무 사이트와, 팔각정과 반려견 동반입장이 가능한(제한된 구역)알프스 사이트가 있다. 캠핑장 입구에서부터 눈길을 끄는 인공연못과 조형물들은 잘 가꾸어진 정원 속에서 빛을 발한다.  가래골농원 캠핑장은 놀거리와 체험거리가 많은 캠핑장이다. 아이들을 위한 미니농장(양, 사슴, 토끼, 염소, 말, 공작새 등)이 있어, 동물들에게 먹이주기 체험도 하며, 승마장이 있어 조랑말을 타보는 승마체험 도할 수 있다. 여름이면 25미터 길이의 워터슬라이드 미끄럼틀 수영장이 있어 짜릿하게 물놀이를 할 수 있다. 산책로가 잘되어 있어 맑은 공기를 마시며 산책을 즐기기에 좋다.",
            allar: "45000",
            insrncAt: "N",
            trsagntNo: "2017-000003호(가래골 농원)",
            bizrno: "104-06-95913",
            facltDivNm: "민간",
            mangeDivNm: "직영",
            mgcDiv: "",
            manageSttus: "운영",
            hvofBgnde: "",
            hvofEnddle: "",
            featureNm:
              "조경 의 아름다움 과 벗나무,소나무,연산홍 등 이 있는  멋진 정원.  미니 동물농장 이라고 해도 어색하지 않는 곳(염소,양,공작,오리.토끼.강아지,말 등) 너른 잔디에 아이들이 맘껏 뛰어놀수 있는 곳. 반려견가 들을 위한 그들만의 공간에서 편히 쉴 수 있는 곳. 소나무,알프스는  11~03월 까지 휴장. 개인카라반 구역이 따로있슴(F구역)",
            induty: "일반야영장",
            lctCl: "산,숲",
            doNm: "경기도",
            sigunguNm: "포천시",
            zipcode: "487921",
            addr1: "경기도 포천시 창수면 추동리 ",
            addr2: "821 ",
            mapX: "127.1592806",
            mapY: "37.9938562",
            direction: "",
            tel: "031-533-7410",
            homepage: "http://garaegol.com/ws/builder/",
            resveUrl: "",
            resveCl: "",
            manageNmpr: "1",
            gnrlSiteCo: "0",
            autoSiteCo: "0",
            glampSiteCo: "0",
            caravSiteCo: "0",
            indvdlCaravSiteCo: "0",
            sitedStnc: "0",
            siteMg1Width: "4",
            siteMg2Width: "5",
            siteMg3Width: "0",
            siteMg1Vrticl: "7",
            siteMg2Vrticl: "8",
            siteMg3Vrticl: "0",
            siteMg1Co: "0",
            siteMg2Co: "0",
            siteMg3Co: "0",
            siteBottomCl1: "0",
            siteBottomCl2: "0",
            siteBottomCl3: "0",
            siteBottomCl4: "0",
            siteBottomCl5: "0",
            tooltip: "",
            glampInnerFclty: "",
            caravInnerFclty: "",
            prmisnDe: "2016-09-13",
            operPdCl: "봄,여름,가을,겨울",
            operDeCl: "평일+주말",
            trlerAcmpnyAt: "Y",
            caravAcmpnyAt: "N",
            toiletCo: "0",
            swrmCo: "0",
            wtrplCo: "0",
            brazierCl: "개별",
            sbrsCl:
              "전기,무선인터넷,장작판매,온수,트렘폴린,물놀이장,놀이터,운동시설,마트.편의점",
            sbrsEtc: "",
            posblFcltyCl: "산책로,강/물놀이,농어촌체험시설",
            posblFcltyEtc: "",
            clturEventAt: "N",
            clturEvent: "",
            exprnProgrmAt: "Y",
            exprnProgrm: "동물먹이주기,승마체험.밤 줍기등",
            extshrCo: "90",
            frprvtWrppCo: "0",
            frprvtSandCo: "0",
            fireSensorCo: "0",
            themaEnvrnCl: "액티비티,여름물놀이,걷기길",
            eqpmnLendCl: "릴선",
            animalCmgCl: "가능",
            tourEraCl: "",
            firstImageUrl:
              "https://gocamping.or.kr/upload/camp/70/thumb/thumb_720_6059nHMzIyRUDXrZF7zXnrBN.jpg",
            createdtime: "2022-08-01 23:17:24",
            modifiedtime: "2022-08-01 23:17:24",
          },
        ],
      },
      numOfRows: 10,
      pageNo: 3,
      totalCount: 3207,
    },
  },
};
